-- RICAZO: Migracao de Produtos do Sistema Antigo
-- Total: 210 produtos (combos excluidos)
-- Gerado automaticamente a partir de Produtos.xlsx
-- Executar no Supabase SQL Editor APOS rodar:
-- ALTER TABLE produtos ADD COLUMN categoria TEXT DEFAULT NULL;

INSERT INTO produtos (nome, preco_base, tipo_preco, ativo, visivel, is_combo, itens_combo, excluido, categoria)
VALUES
  ('ACAI 300ML', 13.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('ACAI 500ML', 17.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('ACAI 770ML', 22.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('AGUA 1,5 CGAS', 6.0, 'unidade', true, true, false, '[]', false, 'AGUAS'),
  ('AGUA 1,5 CRISTAL', 6.0, 'unidade', true, true, false, '[]', false, 'AGUAS'),
  ('AGUA 500ML C/GAS', 4.0, 'unidade', true, true, false, '[]', false, 'AGUAS'),
  ('AGUA C/GAS MILALBA', 4.0, 'unidade', true, true, false, '[]', false, 'AGUAS'),
  ('AGUA MINERAL 500ML', 4.0, 'unidade', true, true, false, '[]', false, 'AGUAS'),
  ('AGUA NESTLE 510ML', 4.0, 'unidade', true, true, false, '[]', false, 'AGUAS'),
  ('ALF. GUAYMALLEN BCO', 9.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF. GUAYMALLEN DDL', 9.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF. GUAYMALLEN DE ORO', 9.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF. GULA 100% PECADO', 12.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF. GULRO', 12.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF. JORGELIN', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF. MAICENA GRANDE', 12.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF OREO', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF PEPITOS', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF RASTA  BCO', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF RASTA NGRO', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF. RASTA TRICO 100G', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('ALF  RICO SABOR', 12.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('BALANZA', 1.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('BOLO/BUDIN C/ DDL', 17.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('BOLO/BUDIN C/ NARANJA', 17.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('BOLO/BUDIN DE CHIPS', 17.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('BROWNIE COM NOZES', 12.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('BUDIN / BOLO', 15.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('CAFE MOLIDO DOPPIO SUL DE MINAS 250G', 50.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('CANONCITO CON DDL', 7.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('CAPUCCINO DUPLO', 15.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('CERVEZA BOHEMIAN PURO MALTE 473ML', 6.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA BRAHMA CHOPP 473ML LATA', 7.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA BRAHMA DUPLO MALTE 473ML LATA', 8.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA BUDWEISER 330ML LONG NECK', 9.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA CORONA 330ML LONG', 12.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA CORONA 473ML LATA', 12.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA HEINEKEN', 9.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA IMPERIO 275ML LONG NECK', 6.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA ORIGINAL ANTARTICA 473ML', 8.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA PATAGONIA AMBER LAGER 350ML', 9.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA PATAGONIA BOHEMIAN PILSENER 350ML LATA', 9.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA PATAGONIA WEISSE 350ML LATA', 9.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA SPATEN 473ML', 8.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA STELLA ARTOIS 473ML LATA', 9.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CERVEZA SULAMERICANA 473MLLATA', 6.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('CHA CLASICO', 10.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('CHOCOLATE QUENTE', 15.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('COCA COLA 1,5 ORIGINAL DESC', 12.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('COCA COLA 350ML LATA', 8.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('COCA COLA KS 290', 5.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('COCA COLA ORIG. 200ML', 4.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('COCA COLA VIDRO 1L RETORNAVEL', 10.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('COCA COLA ZERO 350ML', 8.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('COCA COLA ZERO AZUC. 200ML', 4.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('COOKIE COM CHIPS', 1.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('CROISSANT', 8.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('CROISSANTS C/ PARMA, RUCULA E QUEIJO', 29.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('CROISSANTS C/PEITO PERU E QUEIJO', 22.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('CROISS PyQ', 15.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('DDL ADICIONAL', 4.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('DEL VALLE LARANJA 200ML', 5.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('DOPPIO ALTA MOGIANA 250G', 50.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('DULCE DE LECHE 400G LASERENISIMA', 30.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('DULCE DL COLONIAL 400G', 30.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('DUZIA DE MEIALUAS', 40.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('DUZIA/ DOCENA MEDIA L/ FACTURAS', 45.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('EMPANADAS', 10.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('ESPRESO PEQUENHO', 8.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('ESPRESSO DUPLO', 14.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('ESPRES TONIC', 15.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('FANTA LARANJA 200ML', 4.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('FANTA LARANJA 350ML LATA', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('FANTA MARACUJA 350ML LATA', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('FANTA UVA 200ML', 4.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('FANTA UVA 350ML LATA', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('FATIA LEMON PIE', 20.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('FATIA PRESUNTO', 2.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('FATIA QUEIJO', 2.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('FATIA TARTA TOFFY', 15.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('FERNET BRANCA 750ML', 140.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('FERNET BRANCA MORADOR 750ML', 130.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('FERROCARRIL', 6.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('FLAT WHITE', 14.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('GATORADE LIMAO 500ML', 8.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GATORADE MARAC 500ML', 8.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GATORADE MOR 500ML', 8.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GATORADE TANG. 500ML', 8.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GATORADE UVA 500ML', 8.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GATORADO BLUE 500ML', 8.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GUARANA 200ML', 5.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GUARANA ANTARTICA 350ML', 6.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GUARANA ANTARTICA ZERO 350ML', 6.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GUARAVITA 290ML COPO', 2.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('GUARAVITON 500ML', 6.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('ICE CARAMELO', 17.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('ICE CHOCOLATE', 17.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('ICE CLASICO', 16.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('INFUSAO COM HERVAS', 14.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('KAPO UVA 200ML', 5.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('KIT MATTIOLI', 25.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('LAGRIMA DUPLO', 14.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('LATTE', 14.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('LEITE ADICIONAL', 3.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('LEITE CHOC. PIRAKIDS 200ML', 3.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('LEITE VEGETAL TROCAR', 4.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('MANTECOL 26g', 5.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('MANTECOL 41G', 9.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('MANTEIGA ADICIONAL', 4.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('MATE COCIDO', 10.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('MATE COCIDO TARAGUI C/20 SAQUINHOS', 15.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('MEIA DUZIA MEDIA  L/FACTURAS', 25.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('MILKA DDL', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('MILKA MOUSSE', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('MILKA OREO ALF', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('MILK BCO ALF', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('MINI TARTA DE MORANGO 12CM', 18.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('MISTO QUENTE', 12.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('MISTO QUENTE C/ OVO', 15.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('ML100% MANTECA', 7.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('ML PYQ', 8.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('ML PYQ MANTEIGA', 10.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('MONSTER', 15.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('MONSTER MANGO LOCO', 15.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('MONSTER PEACHY KEEN', 15.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('MONSTER TROPICAL ORANGE', 15.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('MONSTER VERDE', 15.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('OVOS MEXIDOS', 9.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('PALMERITA GG', 12.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('PALMERITA XL', 12.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('PAN CASEIRO UNIDADE', 10.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('PAN C/ DDL E MANTEIGA', 10.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('PAN C/ OVO', 12.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('PAN RECHEADO COM PYQ', 15.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('PAO FRANCES UN', 10.0, 'unidade', true, true, false, '[]', false, 'PAES'),
  ('P/ C MANTEIGA', 7.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('PEPSI 350ML LATA', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('PEPSI BLACK 350ML LATA', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('PF BATATA DOCE', 12.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('PF DOCE DE LEITE', 12.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('PF MEMBRILLO ARGENTI.', 12.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('PORCION BATATA PF', 15.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('PORCION DDL PF', 15.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('PORCION MEMBRILLO PF', 15.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('PORCION MIL HOJAS', 25.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('PRINGLES CREME E CEBOLA X109G', 20.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('PRINGLES ORIGINAL X109G', 20.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('PRINGLES QUEIJO X109G', 20.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('PORCION TARTA DE COCO', 15.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('P TARTA RICOTTA', 15.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('RISTRETTO', 8.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('ROCAMBOLE X KG', 1.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('SANDWICH DE MIGA PYQ', 12.0, 'unidade', true, true, false, '[]', false, 'SALGADOS'),
  ('SCHWEPPES CITRUS 350ML', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('SCHWEPPES CITRUS SA 350ML', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('SCHWEPPES MIXED VODKA CITRUS 250ML', 8.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('SCHWEPPES MIXER SPRITZ 250ML', 8.0, 'unidade', true, true, false, '[]', false, 'CERVEZAS'),
  ('SODA ITALIANA', 16.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SPRITE LIMAO 200ML', 4.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('SPRITE LIMAO 350ML LATA', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('SPRITE LIMAO 350ML SEM ACUCAR', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('SUCO DE LIMAO', 15.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO DEL VALLE ABACAXI 1L CAIXA', 15.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO DEL VALLE CAJU 1L', 15.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('SUCO DEL VALLE LARANJA 1L CAIXA', 15.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO DEL VALLE MANGA 1L CAIXA', 15.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO DEL VALLE MARACUJA 1L CAIXA', 15.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO DEL VALLE PESSEGO 1L CAIXA', 15.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO DEL VALLE PESSEGO 1L CAIXA SAA', 15.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO DE MORANGO', 15.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO KAPO LARANJA 200ML', 5.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO KAPO MACA 200ML', 5.0, 'unidade', true, true, false, '[]', false, 'SUCOS'),
  ('SUCO KAPO MORANGO 200ML', 5.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('SUCO NARAJA', 15.0, 'unidade', true, true, false, '[]', false, 'CAFE DA MANHA/TARDE'),
  ('TARTA CABSHA', 12.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('TARTA DE FRUTOS ROJOS 12CM', 18.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('TARTA TOFFY 15CM', 40.0, 'unidade', true, true, false, '[]', false, 'TARTAS'),
  ('TERRABUSI DDL ALF', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('TERRABUSI TORTA', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('TEST PRODUTO', 0.5, 'unidade', true, true, false, '[]', false, 'PAES'),
  ('TONICA ANTARTICA 350ML', 6.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('TONICA SCHWEPPES 350ML', 7.0, 'unidade', true, true, false, '[]', false, 'REFRIGERANTE'),
  ('T.PINCHADAS', 3.0, 'unidade', true, true, false, '[]', false, 'PAES'),
  ('T.RASPADAS', 3.0, 'unidade', true, true, false, '[]', false, 'PAES'),
  ('TRISHOT ALF', 15.0, 'unidade', true, true, false, '[]', false, 'ALFAJOR'),
  ('UNIDAD MEIA LUA OU FACTURA', 5.0, 'unidade', true, true, false, '[]', false, 'DOCES'),
  ('VERDEFLOR 1KG YERBA MATE', 55.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('VERDE FLOR PEPERINA', 35.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('VERDE FLOR TOMILLO 500G', 35.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('VERD FLOR CEDRON', 35.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('VERD FLOR MANZANILLA', 35.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('VINO ARG. BENJAMIN MALBEC - CABERNET S', 60.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('VINO ARG. CHACABUCO MALBEC', 70.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('VINO ARG. LATITUD 33 MALBEC', 65.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('VINO BCO ARG. LATITUD 33 CHARDONNAY', 70.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('VINO BCO COSECHA TARDIA NORTON', 50.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('VINO FOND DE CAVE MALBEC', 85.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('VINO ROSE ARG. LATITUD 33 MALBEC ROSE', 70.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('VINO TRUMPETER MALBEC', 90.0, 'unidade', true, true, false, '[]', false, 'VINHOS'),
  ('YERBA AMANDA 500G TRADICIONAL', 37.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA CBSE HIERBAS SERRANAS', 37.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA MATE AMANDA 1KG', 50.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA MATE BALDO 500G', 30.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA MATE CANARIAS AMARELA 500G', 25.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA MATE CANARIAS SERENA X500G', 25.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA MATE LA MERCED "DE CAMPO" 500G', 50.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA MATE LA MERCED "DE MONTE" 500G', 50.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA MATE TARAGUI X500G', 35.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA MATE UNION SUAVE X500G', 35.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA'),
  ('YERBA PLAYADITO 500G', 37.0, 'unidade', true, true, false, '[]', false, 'MERCEARIA');